### ISSUE TITLE
Articles with sub-headlines not reading?

### ISSUE THREAD

**Issue by JesperDramsch** [carsonip/alexa-pocket#11]
Hi,

first thanks for the amazing work.

Most articles work really well. However, some that I had imported via pocket directly would not read at all or skip the first chunk.

This one breaks completely:
https://getpocket.com/explore/item/how-to-work-40-hours-in-16-7-the-simple-technique-that-gave-me-my-life-back-1291711976

This one also doesn't work:
https://medium.com/swlh/this-is-how-to-plan-a-day-94dc24135e1f

**Comment by carsonip** [comment]
Hi Jesper, thanks for reporting an issue. I suppose I have read the first one before, and it didn't work. It was due to the private fetching API of pocket producing article HTML that the skill wouldn't understand.

I will look into the these articles and see what's the problem. If it is also the case, I'll do more guessing in the skill to improve the compatibility. I'll get back in a few hours.

**Comment by carsonip** [comment]
The HTML structure returned by the Pocket text content API is kind of unreliable. Still figuring out a way to reliably get the text content for audio from the response.

**Comment by JesperDramsch** [comment]
Could this package help?

https://www.npmjs.com/package/html-to-ssml

**Comment by carsonip** [comment]
I wish. But the problem is actually not that trivial. After it gets the content html from pocket, it needs to parse it into paragraphs, and chunk it into sizes that fits inside the SSML response size limit. On a side note, the html-to-text utilities are unbelievably bad. I'd rather write a custom html-to-text function.

**Comment by carsonip** [comment]
9a97642 should have fixed this. Thanks for motivating me to develop a proper fix to paragraphing.

I am deploying it to production. Stay tuned.

**Comment by JesperDramsch** [comment]
That is amazing. Thank you so much. Any way I can get you a beer?

**Comment by carsonip** [comment]
The updated skill is now live!

A user sent me Ethereum last time, it was great. But most importantly make sure you leave a positive review for the skill. The rating is somewhat low now.
